In [116]:
from scipy.sparse import coo_matrix

In [117]:
import numpy as np

In [118]:
X = np.array([[1,2],[1,1],[5,7]]) # n = 3, d = 2
Y = np.array([1,2,3]) # n = 3
theta = np.array([[1,1],[1,3],[4,5],[7,8]]) # k = 4, d = 2



In [119]:
X_sparse = coo_matrix(X)

In [120]:
X_sparse.toarray()

array([[1, 2],
       [1, 1],
       [5, 7]])

In [121]:
data = np.array([1]*len(Y))
col = np.array(list(range(len(Y))))


In [122]:
Y

array([1, 2, 3])

In [123]:
col

array([0, 1, 2])

In [124]:
data

array([1, 1, 1])

In [125]:
import scipy.sparse as sparse

In [126]:
n,d = X.shape
k = theta.shape[0]
sparse_X = sparse.coo_matrix(X)
sparse_Y = sparse.coo_matrix((np.array([1]*n),(Y,np.array(list(range(n))))))

In [127]:
sparse_Y.toarray()

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [128]:
sparse_X.toarray()

array([[1, 2],
       [1, 1],
       [5, 7]])

In [129]:
sparse_X.power(np.e).toarray()

array([[  1.        ,   6.58088599],
       [  1.        ,   1.        ],
       [ 79.43235917, 198.25066166]])

In [130]:
sparse_theta = coo_matrix(theta)

In [131]:
sparse_X = coo_matrix(X.T)

In [132]:
sparse_X.toarray()

array([[1, 1, 5],
       [2, 1, 7]])

In [133]:
sparse_theta.toarray()

array([[1, 1],
       [1, 3],
       [4, 5],
       [7, 8]])

In [134]:
ps = sparse_theta@sparse_X/2

In [135]:
ps.toarray()

array([[ 1.5,  1. ,  6. ],
       [ 3.5,  2. , 13. ],
       [ 7. ,  4.5, 27.5],
       [11.5,  7.5, 45.5]])

In [136]:
ps_max = ps.max(0).toarray()

In [137]:
ps_max

array([[11.5,  7.5, 45.5]])

In [138]:
ps_max.repeat(4,axis=0)

array([[11.5,  7.5, 45.5],
       [11.5,  7.5, 45.5],
       [11.5,  7.5, 45.5],
       [11.5,  7.5, 45.5]])

In [147]:
ps = sparse_theta@sparse_X

In [153]:
ps = sparse_theta@sparse_X
ps_max = sparse.coo_matrix(ps.max(0).toarray().repeat(k,axis=0))
ps = ps-ps_max

In [154]:
ps.toarray()

array([[-20, -13, -79],
       [-16, -11, -65],
       [ -9,  -6, -36],
       [  0,   0,   0]], dtype=int32)

In [157]:
np.exp(ps)

TypeError: loop of ufunc does not support argument 0 of type csr_matrix which has no callable exp method

In [149]:
ps_sum = ps.sum(0)

In [150]:
ps = ps.power(np.e)


C:\Users\LH\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\scipy\sparse\data.py:117: RuntimeWarning: invalid value encountered in power
  return self._with_data(data ** n)


In [152]:
ps.toarray()

array([[nan, nan, nan],
       [nan, nan, nan],
       [nan, nan, nan],
       [ 0.,  0.,  0.]])

In [3]:
from scipy.sparse import coo_matrix

In [4]:
import numpy as np

In [6]:
x = coo_matrix(np.array([[4,5],
                        [2,3]]))
y = coo_matrix(np.array([[2,0],
                        [0,5]]))
new = x@y
new.toarray()

array([[ 8, 25],
       [ 4, 15]], dtype=int32)

In [10]:
(np.log(new)).toarray()

TypeError: loop of ufunc does not support argument 0 of type csr_matrix which has no callable log method